### ISSUE TITLE
I'd like to use this, is there a license associated with it?

### ISSUE THREAD

**Issue by slyphon** [wayk/CMakeRust#3]
Hey! This saved me hours of work. I'd like to use this code in an open source project I'm working on, but the powers that be will ask what license this code is released under. Is there a particular license you'd be willing to add to this code?

**Comment by ekse** [comment]
This is an oversight on our part, we will add the license right away as MIT/Apache as is usual for Rust code.

**Comment by ekse** [comment]
The license has been added (#4).

**Comment by ekse** [comment]
Let us know how your experience is going and if there are things that are missing for your use case.

**Comment by slyphon** [comment]
thank you so much! I'll be sure to share back once i get things building well :)
